FROM rust:1.90-slim-bookworm AS build

WORKDIR /app

RUN apt update
RUN apt install -y build-essential pkg-config libssl-dev cmake

COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./operator ./operator
COPY ./proxy ./proxy

RUN cargo build --release

FROM rust:1.90-slim-bookworm
COPY --from=build /app/target/release/controller .
CMD ["./controller"]
