apiVersion: v1
kind: Namespace
metadata:
  name: prj-mainnet-test
---
apiVersion: demeter.run/v1alpha1
kind: CardanoNodePort
metadata:
  name: mainnet-user
  namespace: prj-mainnet-test
spec:
  network: "preview"
  version: "v1"
  throughputTier: "0"
---
apiVersion: demeter.run/v1alpha1
kind: CardanoNodePort
metadata:
  name: mainnet-user-2
  namespace: prj-mainnet-test
spec:
  network: "preview"
  version: "v1"
  throughputTier: "1"